apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8090
    port: 8090
    nodePort: 30016
 selector:
  app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-microservice
        imagePullPolicy: Always
        image: ansvohra/api-gateway
        ports:
        - containerPort: 8090