apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
 type: LoadBalancer
 ports:
  - targetPort: 3000
    port: 3000
    nodePort: 30012
 selector:
  app: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: front-end
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end-microservice
        imagePullPolicy: Always
        image: ansvohra/frontend
        ports:
        - containerPort: 3000