language: node
node: 10
sudo: false

services:
  - docker

script:
  - npm install bcrypt 
  - npm install nodemon
  - npm install

after_success:
  - sudo apt --assume-yes install docker.io
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=ansvohra/frontend
  - docker build -t ansvohra/frontend:latest .
  - docker push ansvohra/frontend:latest
  -	chmod 400 vdn_ssh.pem
  -	ssh -o StrictHostKeyChecking=no -i vdn_ssh.pem ubuntu@149.165.168.66 uptime
  -	ssh -i vdn_ssh.pem ubuntu@149.165.168.66 " rm -rf VignyaanDwaarNirman &&
  -	git clone https://github.com/airavata-courses/VignyaanDwaarNirman.git &&
  -	cd VignyaanDwaarNirman &&
  -	git pull &&
  -	git checkout kubectl &&
  -	cd frontend && 
  -	export KUBECONFIG=/etc/kubernetes/admin.conf
  -	kubectl delete service frontend &&
  - kubectl delete deployment frontend &&
  -	kubectl apply -f config.yaml