language: node_js
node_js: 10.16
sudo: false

services:
  - docker

script:
  - npm install bcrypt 
  - npm install nodemon
  - npm install
     
after-success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t ansvohra/user-management:latest .
    - docker push teamyoda/user-management:latest    
