language: node_js
node_js: 10.16
sudo: false

services:
  - docker

script:
  - npm install bcrypt 
  - npm install nodemon
  - npm install
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=ansvohra/session_management
  - docker build -t ansvohra/session_management:latest .
  - docker push ansvohra/session_management:latest
