language: node_js
node_js: 10.16
sudo: false

services:
  - docker

script:
  - npm install bcrypt 
  - npm install nodemon
  - npm install
     
  after-success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=ansvohra/user-management
    - docker build -t ansvohra/user-management:latest .
    - docker push ansvohra/user-management:latest
    - git clone https://github.com/airavata-courses/VignyaanDwaarNirman.git
    - cd VignyaanDwaarNirman
    - git pull
    - git checkout dockerize_userManagement
    - chmod 400 vdn_ssh.pem
    - cat Dockerfile
    - ssh -o StrictHostKeyChecking=no -i vdn_ssh.pem ubuntu@149.165.168.66 uptime
    - ssh -i vdn_ssh.pem ubuntu@149.165.168.66 "sudo rm -rf VignyaanDwaarNirman && git clone https://github.com/airavata-courses/VignyaanDwaarNirman.git && cd VignyaanDwaarNirman && git checkout kubectl && cd user-management && export KUBECONFIG=/etc/kubernetes/admin.conf && sudo kubectl delete service usermanagement && sudo kubectl delete deployment usermanagement && sudo kubectl apply -f config.yaml"
  