version: "3"
services:
  rabbit:
      hostname: rabbit
      image: rabbitmq
      ports:
        - "5674:5672"  # we forward this port because it's useful for debugging
        - "15674:15672"  # here, we can access rabbitmq management plugin

  front-end:
    build: "./FrontEnd"
    ports:
      - "3000:3000"

  api-gateway:
    build: "./ApiGateway/api-gateway"
    ports:
      - "8090:8090"
    depends_on:
      - rabbit

  user-management:
    build: "./UserManagement"
    ports:
      - "5000:5000"
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  session-management:
    build: "./SessionManagement"
    ports:
      - "7000:7000"
    depends_on:
      - rabbit
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  data-retrival:
    build: "./DataRetrival"
    depends_on:
      - rabbit

  model-execution:
    build: "./ModelExecution"
    depends_on:
      - rabbit

  model-analysis:
    build: "./ModelAnalysis"
    depends_on:
      - rabbit

  # db:
    # image: mongo
    # ports:
      # - "27017:27017"

  # nodejs:
    # image: node:10

  # py:
    # image: continuumio/miniconda3

  # jdk:
    # image: openjdk:11.0.6-jre-slim-buster


  # nginx:
    # image: nginx:latest
    # ports:
      # - "8080:8080"
    # volumes:
      # - ./web/public:/srv/www/static
      # - ./default.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
      # - FrontEnd
      # - UserManagement
      # - SessionManagement
      # - DataRetrival
      # - ModelAnalysis
      # - ModelExecution
