version: "2.1"
services:
  rabbit:
    hostname: rabbit
    build: "./rabbit_server"
    ports: 
        - "15672:15672"
        - "5672:5672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  frontend:
    build: "./FrontEnd"
    hostname: frontend
    ports:
      - "3000:3000"

  apigateway:
    build: "./ApiGateway/api-gateway"
    hostname: apigateway
    ports:
      - "8090:8090"
    links:
      - rabbit
      - frontend
      - usermanagement
      - sessionmanagement

  usermanagement:
    build: "./UserManagement"
    hostname: usermanagement
    ports:
      - "5000:5000"
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  sessionmanagement:
    build: "./SessionManagement"
    hostname: sessionmanagement
    ports:
      - "7000:7000"
    depends_on:
      rabbit:
        condition: service_healthy
    links:
      - rabbit
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  dataretrival:
    build: "./DataRetrival"
    hostname: dataretrival
    depends_on:
      rabbit:
        condition: service_healthy
    links:
      - rabbit

  modelexecution:
    build: "./ModelExecution"
    hostname: modelexecution
    depends_on:
      rabbit:
        condition: service_healthy
    links:
      - rabbit

  modelanalysis:
    build: "./ModelAnalysis"
    hostname: modelanalysis
    depends_on:
      rabbit:
        condition: service_healthy
    links:
      - rabbit